services:
# FireFly Core 
  firefly:
    image: ghcr.io/hyperledger/firefly:v1.4.0-rc.1
    container_name: firefly
    command: 
      --config /etc/firefly/firefly-core.yaml
    volumes:
       - ./firefly-core.yaml:/etc/firefly/firefly-core.yaml:ro
    ports:
      - "5000:5000"
      - "6000:6000"
    depends_on:
      firefly-cardanoconnect:
          condition: service_started
      firefly-cardanosigner:
          condition: service_started
      postgres:
          condition: service_healthy
      
  # cardano connector
  firefly-cardanoconnect:
    image: ghcr.io/hyperledger/firefly-cardanoconnect:latest
    container_name: firefly-cardanoconnect

    command:
      - "/app/firefly-cardanoconnect"
      - "--config-file"
      - "/app/config.yaml"

    environment:
      FIREFLY_URL:                                "http://firefly:5000"
      FIREFLY_CONNECTOR_BLOCKCHAIN_BLOCKFROST_KEY: "previewAe2uMQNis3wntrX0BQtZ5G5i9jyFPsIu"

    ports:
      - "5018:5018"

    volumes:
      - ./connect.yaml:/app/config.yaml

# backend
  backend:
    build: ./backend
    container_name: energy-backend
    ports:
      - "4000:4000"
    environment:
      FIREFLY_URL: "http://firefly:5000"
    depends_on:
      - firefly

# frontend
  frontend:
    build: ./frontend
    container_name: energy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  postgres:
    image: postgres
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_PASSWORD: f1refly
    volumes:
        - firefly-db:/var/lib/postgresql/data
    ports:
        - 5104:5432
    healthcheck:
        test:
            - CMD-SHELL
            - pg_isready -U postgres
        interval: 5s
        timeout: 3s
        retries: 12

  firefly-cardanosigner:
    image: ghcr.io/hyperledger/firefly-cardanosigner:main
    container_name: firefly-cardanosigner

    command:
      - "/app/firefly-cardanosigner"
      - "--config-file"
      - "/app/config.yaml"

    ports:
      - "8555:8555"

    volumes:
      - ./cardanosigner-config.yaml:/app/config.yaml:ro
      - firefly-db:/app/db
    depends_on:
      - firefly-cardanoconnect
  ipfs:
        container_name: ipfs_0
        image: ipfs/go-ipfs:v0.10.0
        environment:
            IPFS_SWARM_KEY: |-
                /key/swarm/psk/1.0.0/
                /base16/
                f2092cb9220c090fa4110ef040c74afb732a9b38ef2a4a5b1722c98ce4ec2483
            LIBP2P_FORCE_PNET: "1"
        volumes:
            - ipfs_staging_0:/export
            - ipfs_data_0:/data/ipfs
        ports:
            - 10206:5001
            - 10207:8080
        healthcheck:
            test:
                - CMD-SHELL
                - wget --post-data= http://127.0.0.1:5001/api/v0/id -O - -q
            interval: 5s
            timeout: 3s
            retries: 12
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
  dataexchange_0:
    container_name: dataexchange_0
    image: ghcr.io/hyperledger/firefly-dataexchange-https@sha256:1e01b0d5fc3cfd95de150d47c09ba419b8ec98345d105a6d67d7bc7101aeea89
    volumes:
      - ./dataexchange_0:/data:ro
    ports:
      - 10205:3000
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

volumes:
  firefly-db:
  ipfs_data_0: {}
  ipfs_staging_0: {}
  dataexchange_0: {}