services:
# core instances
  firefly_core_00:
    image: ghcr.io/hyperledger/firefly:v1.4.0-rc.1
    container_name: firefly_core_00
    command: 
      --config /etc/firefly/firefly-core.yaml
    volumes:
       - ./firefly-core00.yaml:/etc/firefly/firefly-core.yaml:ro
    ports:
      - "5000:5000"
      - "5101:5101"
    depends_on:
      cardanoconnect_00:
          condition: service_started
      cardanosigner_00:
          condition: service_started
      dataexchange_00:
          condition: service_started
      postgres:
          condition: service_healthy
    
 # cardano connector
  cardanoconnect_00:
    image: ghcr.io/hyperledger/firefly-cardanoconnect:0.5.0-20250711-18
    container_name: cardanoconnect_00
    build:
      context: ..
      target: firefly-cardanoconnect
    develop:
      watch:
      - action: rebuild
        path: ../firefly-cardanoconnect
    command:
      - "/app/firefly-cardanoconnect"
      - "--config-file"
      - "/app/config.yaml"
    environment:
      FIREFLY_URL:                                "http://firefly_core_00:5000"
      FIREFLY_CONNECTOR_BLOCKCHAIN_BLOCKFROST_KEY: "previewAe2uMQNis3wntrX0BQtZ5G5i9jyFPsIu"
    ports:
      - 5018:5018
    volumes:
      - ./connect00.yaml:/app/config.yaml
      - connect-contracts:/contracts
      - connect-db:/db

  cardanosigner_00:
    image: ghcr.io/hyperledger/firefly-cardanosigner:main
    container_name: cardanosigner_00
    command:
      - "/app/firefly-cardanosigner"
      - "--config-file"
      - "/app/config.yaml"
    ports:
      - "8555:8555"
    volumes:
    - ./signer00.yaml:/app/config.yaml:ro
    - ./wallet_00:/wallet
    depends_on:
      - cardanoconnect_00
        
  ipfs_00:
        container_name: ipfs_00
        image: ipfs/go-ipfs:v0.10.0
        environment:
            IPFS_SWARM_KEY: |-
                /key/swarm/psk/1.0.0/
                /base16/
                f2092cb9220c090fa4110ef040c74afb732a9b38ef2a4a5b1722c98ce4ec2483
            LIBP2P_FORCE_PNET: "1"
        volumes:
            - ipfs_staging_00:/export
            - ipfs_data_00:/data/ipfs
        ports:
            - 10206:5001
            - 10207:8080
        healthcheck:
            test:
                - CMD-SHELL
                - wget --post-data= http://127.0.0.1:5001/api/v0/id -O - -q
            interval: 5s
            timeout: 3s
            retries: 12
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
  postgres:
    image: postgres
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_PASSWORD: f1refly
    volumes:
        - firefly-db:/var/lib/postgresql/data
    ports:
        - 5104:5432
    healthcheck:
        test:
            - CMD-SHELL
            - pg_isready -U postgres
        interval: 5s
        timeout: 3s
        retries: 12

  dataexchange_00:
    container_name: dataexchange_00
    image: ghcr.io/hyperledger/firefly-dataexchange-https@sha256:1e01b0d5fc3cfd95de150d47c09ba419b8ec98345d105a6d67d7bc7101aeea89
    volumes:
      - ./dataexchange_00:/data:ro
    ports:
      - 10205:3000
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

volumes:
  connect-contracts:
  connect-db:
  ipfs_data_00: {}
  ipfs_staging_00: {}
  dataexchange_00: {}
  firefly-db: